// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wznfhzhirahvhcmsbfjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6bmZoemhpcmFodmhjbXNiZmpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTc4NzYsImV4cCI6MjA2NTU5Mzg3Nn0.rhmjnpFmg_MKCE5pvfF0UImrxPQgYXQMOeOlA2DJYEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);